### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by sandeesaripalli** [nik-base/auto-tfs#1]
Hi Nikhil,

I am getting this error TF command 'checkout' error: TF30063: You are not authorized to access.

Where can I give my PAT token?

Looking forward for your reply.

**Comment by nik-base** [comment]
Hi Sandeep,

Can you check if you can access TFS from the browser inside the visual studio. You will find the browser in View->Other Windows->Web Browser. Use your TFS url in navigation bar to access the TFS. If you get unauthorized error here, then try login to TFS here. Also, make sure you have appropriate rights for the item you are trying to checkout. If the issue persists, try restarting system/visual studio. 

Let me know if it helps.

**Comment by sandeesaripalli** [comment]
for some reason, I am able to navigate to TFS url in regular chrome or FF browser but not from the visual studio->Other Windows-> Web Browser :(

**Comment by nik-base** [comment]
You are not able to navigate to TFS url or getting some error? You can login from here if it possible to transverse to login page. Or you can try removing the connection and adding it again. Also, try clearing the TFS credentials in credential manager and then again try  with the visual studio web browser.

**Comment by sandeesaripalli** [comment]
![image](https://user-images.githubusercontent.com/410096/130088402-b70d6f7f-7f6b-4dea-8af9-db4e53563c31.png)

**Comment by sandeesaripalli** [comment]
Just getting that error will try clearing credential manager tfs details and try logging again

**Comment by sandeesaripalli** [comment]
![image](https://user-images.githubusercontent.com/410096/130088718-7f8497e9-041f-4d42-866f-584266fe03dc.png)

**Comment by nik-base** [comment]
The extension relied on the TF command. You can try executing the TF command manually by traversing to the path where TF.exe is then execute any TF command. For example - TF status <Local Path of any mapped workspace/folder/item>

**Comment by sandeesaripalli** [comment]
I tried that but every time I had to set like this in powershell
PS C:\> Set-Alias tfs "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe"

and after that for every file status it's asking me credentials I know it's more related to TFS

**Comment by nik-base** [comment]
Here are some links which have some solution for same issue -

https://www.codewrecks.com/post/old/2014/07/your-tfs-keeps-asking-you-for-credentials-even-with-active-directory/

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/559895b1-b4d9-4267-8487-0bc6e47ad4d7/team-explorer-and-tfexe-ignoring-my-saved-usernamepassword?forum=tfsgeneral

https://social.msdn.microsoft.com/Forums/vstudio/en-US/84b4749c-2838-4975-9b61-991cb90582b4/always-prompted-for-login-credentials?forum=tfsgeneral

**Comment by nik-base** [comment]
Closing as related to TFS itself. Feel free to reopen / create separate discussion.
