### ISSUE TITLE
TF command 'checkin' error: The actual comment is not saved

### ISSUE THREAD

**Issue by FredyValstrauss** [nik-base/auto-tfs#11]
When using Auto TFS v1.3.5 on VSCode 1.81.1 whenever I do a checkin, the Check-in Comment is not saved in TFS, and an error is thrown in VSCode, like:

TF command 'checkin' error: There is no pending change for 'every'.
There is no pending change for 'single'.
There is no pending change for 'word'.
There is no pending change for 'on'.
There is no pending change for 'the'.
There is no pending change for 'check-in'.
There is no pending change for 'comment.\'.

Do you think you could take a look at this? Thank you

**Comment by nik-base** [comment]
Hi @FredyValstrauss , Thank you identifying and raising the issue. I will take a look at this as soon as possible.

**Comment by FredyValstrauss** [comment]
Hi Nik,
Thank you for you rapid work. I tried to do a checkin and no error was thrown and the message was stored successfully, although, the message included single quotes at the beginning and end of the comment. This is only a cosmetic issue, I believe, so I'm not sure if it is worth fixing. Another cosmetic issue is that the checkin comment stays on the textarea even when the checkin was successfull. Thanks for your work!

**Comment by nik-base** [comment]
Hi @FredyValstrauss , thanks for identifying this, since I currently have no way to test this functionality myself. I will be reopen the issue and have a look at this.

**Comment by nik-base** [comment]
@FredyValstrauss , Will it be possible for you to test the issue if I provide the extension (.vsix file), since I am unable to do so. If it works I can release the new version on marketplace.

**Comment by FredyValstrauss** [comment]
Sure thing, I can test it for you. Please send me the file.

**Comment by FredyValstrauss** [comment]
Hi Nik,
I tested the file and is working perfectly fine now. The comment was stored correctly without single quotes, and the comment was deleted from the textarea once checked in. I use TFS 2012 and let me tell you, your app is the only one that works for me on VSCode. Great work!

**Comment by nik-base** [comment]
@FredyValstrauss , That's good new! Thanks a lot for testing it for me and thank you for your kind words!
